services:
  flasktts:
    image: ghcr.io/derekparks/flasktts:latest
    container_name: flasktts
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - ./db:/FlaskTtS/db/
      - ./style2tts_workdir:/FlaskTtS/style2tts_workdir
      - ./huggingface:/root/.cache/huggingface/
    environment:
      - HUEY_DB_PATH=/FlaskTtS/db/huey.db
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
