services:
  flasktts:
    image: ghcr.io/DerekParks/flasktts:latest
    container_name: flasktts
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - ./huey.db:/FlaskTtS/huey.db
      - ./style2tts_workdir:/FlaskTtS/style2tts_workdir
